### ISSUE TITLE
Tonkeeper - IOS - When you click on last transaction error is occurred and app is being freezed

### ISSUE THREAD

**Issue by artitanov** [tonkeeper/wallet#7] opened 2022-09-16 14:58 UTC
### Bug Type

Functional

### Reproduction steps

1. Open Tonkeeper
2. Click on last transaction
3. Error occured while loading transaction.
4. There are two options but no one is clickable

### Actual result

App is being freezed.
Closing the app and re-launch is not working. I’m not able to to do anything in app.
![CF44AE2A-2F0D-4F68-A33C-0FBA0D236795](https://user-images.githubusercontent.com/45713886/190669024-32d0ab84-dede-4b8f-ac0d-6d86e8a4bd6f.png)

### Expected result

Opportunity to copy log or restart app by clicking such button is available

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):

Device: iphone xs
OS: ios 15.6.1
Browser tonkeeper app
Version 2.6

### Additional Context

Not rooted

**Comment by MariaBit** [comment] 2022-10-04 16:33
Hi, I believe this issue has been already fixed. Could you check if the issue is still reproducible on your device?
If it would be reproducible please record the video with your steps. It will help us to catch the issue.
Thanks!

**Comment by MariaBit** [comment] 2022-10-20 18:18
We were able to catch the issue. It has been registered with internal number TK-828.
You will get PR number when it will be fixed.

Thanks!

**Comment by olyaMay** [comment] 2023-11-02 23:35
Fixed.

**Closed by olyaMay** 2023-11-02 23:35 UTC
Labels: bug
