### ISSUE TITLE
Notifications are not working

### ISSUE THREAD

**Issue by algrishina** [tonkeeper/wallet#63] opened 2022-09-24 20:02 UTC
### Bug Type

UX

### Reproduction steps

1. Go to settings
2. Try to enable “Notifications”

### Actual result

Error “Notifications are not supported on your device”

### Expected result

Notifications are enabled

### Suggested Severity

Medium

### Device

Smartphone (please complete the following information):
- Device: iPhone 12 Pro Max
- OS: 16.0
Tonkeeper 2.6

### Additional Context

The same problem was during the first installation. Modal window to enable notifications was not working, the only option was only to skip this step

Although in the settings I see that notifications are enabled

[Video to reproduce the error](https://drive.google.com/file/d/1i6MwCsT68nXUu1Vt2WpKHBgQJBMuHY-y/view?usp=drivesdk)

**Comment by olyaMay** [comment] 2022-09-29 10:28
Hi, the issue has been registered in our system with internal ТК-781.
You will get a notification when it will be fixed. Thanks!

**Comment by MariaBit** [comment] 2022-09-30 10:47
Hi! The issue is fixed.

**Closed by MariaBit** 2022-09-30 10:47 UTC
Labels: bug

**Comment by mehrdadsdn** [comment] 2024-09-05 19:29
hi
i have a transaction in tonkeeper and faild but all of the ton coin and dogs is  zeroo! how i do
plz help

**Comment by Tonytech-wq** [comment] 2024-09-05 19:31
@mehrdadsdn Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by MariaBit** [comment] 2024-09-05 19:48
Hi, please contact Tonkeeper support using link in Tonkeeper app: Settings (gear icon in the top right corner) -> Support.

**Comment by mehrdadsdn** [comment] 2024-09-05 20:02
tonkeeper 
support only answers a series of pre-prepared questions and does not work at all
