### ISSUE TITLE
Android App - Buy TON- Mercuryo broken link

### ISSUE THREAD

**Issue by jejimenez** [tonkeeper/wallet#3] opened 2022-09-16 12:57 UTC
### Bug Type

Functional

### Reproduction steps

1. Open Tonkeeper Adroid app
2. Go to BUY
3. Go to Mercuryo
4. Click Open Mercuryo

### Actual result

Black screen.  Looks like it's trying to load but nothing happens. 
The black screen is intermittently showing a message "403 Forbidden"
<img src="https://user-images.githubusercontent.com/310281/190644120-388e1c44-6e13-4429-8e8c-aa8503dba839.jpg" alt="Your image title" width="300"/>
<img src="https://user-images.githubusercontent.com/310281/190644126-79d584dd-031d-40fd-b30f-4e9546125136.jpg" alt="Your image title" width="300"/>

### Expected result

Mercuryo screen to buy TON

### Suggested Severity

Medium

### Device

Smartphone:
- Device: Xiaomi 11 Lite
- OS: Android 11
- Browser: NA
- Version NA

**Comment by MariaBit** [comment] 2022-09-21 17:53
Hello, could you please check if it is still reproducible on your device? 
Probably it was a temporary issue on Mercuryo side. 

Thanks in advance!

**Comment by jejimenez** [comment] 2022-09-21 19:40
Hi!  I just tried. Getting the same behavior. You can see in this screen record :
[Black screen when going to Mercuryo](https://drive.google.com/file/d/1HZV05q61P3qDJtgevON5aAaWHl9bcK0y/view?usp=sharing)

**Comment by MariaBit** [comment] 2022-09-22 10:10
Thanks! Could you check if Neocrypro opens on your device?

**Comment by jejimenez** [comment] 2022-09-23 03:41
Yeah! Neocrypto opens in my device.
I just tryed with Mercuryo to open directly from my device and my laptop, in both Mercuryo is getting 403 Forbidden.

**Comment by MariaBit** [comment] 2022-09-26 11:04
Thanks for the update. We are looking into it.

**Comment by MariaBit** [comment] 2022-10-03 11:24
Probably the issue is related with your location.
Could you try to open Mercuryo with any VPN service turned on?

**Comment by MariaBit** [comment] 2022-11-01 19:04
I'm closing this item because there is no answer. I believe the problem has been resolved.

**Closed by MariaBit** 2022-11-01 19:04 UTC
Labels: question
