### ISSUE TITLE
tonkeeper website bug

### ISSUE THREAD

**Issue by Antohazp** [tonkeeper/wallet#2] opened 2022-09-16 12:39 UTC
### Bug Type

Functional

### Reproduction steps

1.Go to website https://tonkeeper.com/
2. Click "Support" button (on the top right part of page, or in the end of page left part
![tonkeeper_bug1](https://user-images.githubusercontent.com/87418719/190640512-349d9a46-3b94-46bc-b8a5-af4e935557b2.jpg)
![image](https://user-images.githubusercontent.com/87418719/190641171-4b8b921f-b4f3-4850-a9c7-d3a535561580.png)

### Actual result

Nothing happening

### Expected result

Should open support mailing page 

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):
- OS: [Windows 10 Pro]
- Browser BRAVE
- Version [v1.43.93]

**Comment by MariaBit** [comment] 2022-09-22 08:57
Hi, for me it works fine in Browser BRAVE v1.43.93.
Could you please check if it works for you in another browser like Chrome or Mozilla Firefox?
Also I would recommend you to clear Brave browser cache and check if the issue with support button will be still reproducible.
Thanks!

**Comment by MariaBit** [comment] 2022-10-03 11:10
I hope that the comment above resolved the problem on your machine. 
So I'm closing this ticket, because there is no answer.

**Closed by MariaBit** 2022-10-03 11:10 UTC
Labels: question
