### ISSUE TITLE
Transfer of NFT available after this nft was sent

### ISSUE THREAD

**Issue by stuxjkee** [tonkeeper/wallet#129] opened 2022-11-16 21:44 UTC
### Bug Type

UI

### Reproduction steps

1. Receive telegram username nft
2. Send this nft to another wallet
3. Go to transaction history
4. Click on telegram username nft that was sent 

https://user-images.githubusercontent.com/6277505/202300971-e6328e8a-fc90-44d3-af28-5217e9a523fd.MP4

### Actual result

"Transfer" functionality available for nft that was sent 

### Expected result

"Transfer" functionality should not be available for nft that was sent 

### Suggested Severity

Medium

### Device

Apple IOS 16.1
Safari

**Comment by MariaBit** [comment] 2023-01-23 22:11
Hello! An issue for disabling "Transfer" button will be fixed together with showing correct address of new nft owner.
So I would say the issue is a duplicate. Please follow #62  for updates. Thanks!

**Closed by MariaBit** 2023-01-23 22:11 UTC
