### ISSUE TITLE
Tonkeeper - IOS - When you click on send button, history of addresses are available but the address is not shown (e.g. start and end of address) 

### ISSUE THREAD

**Issue by artitanov** [tonkeeper/wallet#6] opened 2022-09-16 14:55 UTC
### Bug Type

Functional

### Reproduction steps

1. Open Tonkeeper
2. Click on [send] button
3. History of last addresses are available, but addresses can not be defined

### Actual result

History of last addresses are available, but addresses can not be defined
![48C899A6-8BCA-4504-88FA-B7E8C30B42A7](https://user-images.githubusercontent.com/45713886/190668395-9ea9927a-1a9f-4c39-83a5-dcd57af9802c.jpeg)

### Expected result

History of last addresses are available, addresses can be defined (e.g. start and end of address)

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):

Device: iphone xs
OS: ios 15.6.1
Browser tonkeeper app
Version 2.6

### Additional Context

Not rooted

**Comment by MariaBit** [comment] 2022-10-04 16:24
Hi, could you please check if the issue with recent addresses list is still reproducible?

**Comment by MariaBit** [comment] 2022-11-01 19:09
I'm closing the issue because there is no answer. I believe that the problem has been resolved.

**Closed by MariaBit** 2022-11-01 19:09 UTC
Labels: question
